version: "2"

linters:
  enable:
    - errcheck
    - gocritic
    - staticcheck

  settings:
    gocritic:
      enabled-checks:
        - rangeValCopy
        - rangeExprCopy

    staticcheck:
      checks: ["all"]
