name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Build
      run: go build ./...

    - name: Vet
      run: go vet ./...

    - name: Verify dependencies
      shell: bash
      run: |
        go mod tidy -v
        git diff --exit-code go.mod
        if [ -f go.sum ]; then git diff --exit-code go.sum; fi

    - name: Compile benchmarks
      shell: bash
      run: go list ./... | xargs go test -run=^$ -bench=.

    - name: Run unit tests
      run: go test -short -v ./...

    - name: Run all tests (including integration)
      run: go test -v ./...

    - name: Coverage report
      if: matrix.os == 'ubuntu-latest'
      run: |
        go test -coverprofile=coverage.out -covermode=atomic ./...
        go tool cover -func=coverage.out
